[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\t/home/box)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0H\0\0\xe\xff\0\0\bT\0\0\0\0\0\0\0H\0\0\xe\xff\0\0\bT\0\0\0\0\0\0\0\0\xf\0\0\0\0\0\0\0\0H\0\0\xe\xff\0\0\bT)

[FullScreen]
pos=@Point(1520 2090)
screen=@Rect(0 0 3840 2160)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(3840 1968)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/box/Videos/vokoscreenNG-2020-07-20_22-45-12.mkv
times=0
