- name: Apt Update and Upgrade
  hosts: home
  tasks:
    - name: Run the equivalent of "apt-get update"
      become: true
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
    - name: Update all packages to their latest version
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest
